version = 1
SPDX-PackageName = "Bash Shell 腳本語言"
SPDX-PackageSupplier = "Issues · libre-knowledge/bash-scripting-language <https://github.com/libre-knowledge/bash-scripting-language/issues>"
SPDX-PackageDownloadLocation = "https://github.com/libre-knowledge/bash-scripting-language"

[[annotations]]
path = ["**README.md", "**/README.md", "_config.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 自由知識協作平台貢獻者 <https://github.com/libre-knowledge/libre-knowledge/issues>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
